package catalog

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"maps"
	"slices"
	"strings"
)

// paramTypes are the placeholders with a fixed Go type, so passing the
// wrong thing is a compile error; the rest take any.
var paramTypes = map[string]string{"n": "int", "err": "error"}

// Generate writes package str's keys_gen.go for the English catalog. prev
// is the keys_gen.go it replaces (nil for none): an entry's parameters
// keep the order they had there, so rewording a template can't silently
// swap the arguments at its call sites. New parameters follow, in reading
// order.
func Generate(en, prev []byte) ([]byte, error) {
	c, err := Parse(en)
	if err != nil {
		return nil, err
	}
	was, err := signatures(prev)
	if err != nil {
		return nil, err
	}
	var b bytes.Buffer
	b.WriteString("// Code generated by go generate ./internal/str from locales/en.toml. DO NOT EDIT.\n\npackage str\n")
	funcs := map[string]string{}
	for _, key := range slices.Sorted(maps.Keys(c)) {
		e := c[key]
		name := FuncName(key)
		if other, ok := funcs[name]; ok {
			return nil, fmt.Errorf("%s and %s both make %s", other, key, name)
		}
		funcs[name] = key

		params := keepOrder(e.Params(), was[name])
		var sig, pairs []string
		for i, p := range params {
			id := p
			if token.IsKeyword(p) {
				id += "_"
			}
			pairs = append(pairs, fmt.Sprintf("%q: %s", p, id))
			typ := paramTypes[p]
			if typ == "" {
				typ = "any"
			}
			if i+1 < len(params) && typeOf(params[i+1]) == typ {
				sig = append(sig, id)
			} else {
				sig = append(sig, id+" "+typ)
			}
		}
		args := "nil"
		if len(pairs) > 0 {
			args = "map[string]any{" + strings.Join(pairs, ", ") + "}"
		}

		b.WriteString("\n")
		if !e.Plural() {
			fmt.Fprintf(&b, "// %s is %s: %s\n", name, key, quoteForComment(e.Forms[""]))
			fmt.Fprintf(&b, "func %s(%s) string { return get(%q, %s) }\n", name, strings.Join(sig, ", "), key, args)
			continue
		}
		fmt.Fprintf(&b, "// %s is %s, by count:\n", name, key)
		for _, form := range Forms {
			if t, ok := e.Forms[form]; ok {
				fmt.Fprintf(&b, "//   - %s: %s\n", form, quoteForComment(t))
			}
		}
		fmt.Fprintf(&b, "func %s(%s) string { return count(%q, n, %s) }\n", name, strings.Join(sig, ", "), key, args)
	}
	return format.Source(b.Bytes())
}

func typeOf(p string) string {
	if t := paramTypes[p]; t != "" {
		return t
	}
	return "any"
}

// keepOrder orders params as they were (those still there), then the
// new ones. A plural's n stays first.
func keepOrder(params, was []string) []string {
	var out []string
	if len(params) > 0 && params[0] == "n" {
		out = append(out, "n")
	}
	for _, p := range was {
		if slices.Contains(params, p) && !slices.Contains(out, p) {
			out = append(out, p)
		}
	}
	for _, p := range params {
		if !slices.Contains(out, p) {
			out = append(out, p)
		}
	}
	return out
}

// signatures reads each generated function's parameter names from a
// previous keys_gen.go.
func signatures(src []byte) (map[string][]string, error) {
	out := map[string][]string{}
	if len(src) == 0 {
		return out, nil
	}
	f, err := parser.ParseFile(token.NewFileSet(), "keys_gen.go", src, 0)
	if err != nil {
		return nil, fmt.Errorf("reading the old keys_gen.go: %w", err)
	}
	for _, d := range f.Decls {
		fd, ok := d.(*ast.FuncDecl)
		if !ok {
			continue
		}
		for _, fld := range fd.Type.Params.List {
			for _, n := range fld.Names {
				out[fd.Name.Name] = append(out[fd.Name.Name], strings.TrimSuffix(n.Name, "_"))
			}
		}
	}
	return out, nil
}

// FuncName is the generated function's name for a key:
// browse.lines_in_range is BrowseLinesInRange.
func FuncName(key string) string {
	var b strings.Builder
	for _, part := range strings.FieldsFunc(key, func(r rune) bool { return r == '.' || r == '_' }) {
		b.WriteString(strings.ToUpper(part[:1]) + part[1:])
	}
	return b.String()
}

// quoteForComment renders a template for a one-line doc comment.
func quoteForComment(t Template) string { return fmt.Sprintf("%q", t.String()) }

// WebJSON is the catalog's [web] table as JSON, keys without "web.", for
// the web page (web/static/strings.json). The page fills {name}
// placeholders and nothing else, so plural entries, fmt verbs and literal
// braces are errors here.
func WebJSON(en []byte) ([]byte, error) {
	c, err := Parse(en)
	if err != nil {
		return nil, err
	}
	out := map[string]string{}
	for k, e := range c {
		name, ok := strings.CutPrefix(k, "web.")
		if !ok {
			continue
		}
		if e.Plural() {
			return nil, fmt.Errorf("%s: the page can't show plural entries", k) //str:ok
		}
		for _, s := range e.Forms[""] {
			if s.Name != "" && s.Verb != "%v" {
				return nil, fmt.Errorf("%s: the page can't use fmt verbs", k) //str:ok
			}
			if s.Name == "" && strings.ContainsAny(s.Text, "{}") {
				return nil, fmt.Errorf("%s: the page can't show braces", k) //str:ok
			}
		}
		out[name] = e.Forms[""].String()
	}
	b, err := json.MarshalIndent(out, "", "  ") // map keys come out sorted
	return append(b, '\n'), err
}
