// Code generated by go generate ./internal/str from locales/en.toml. DO NOT EDIT.

package str

// BrowseCopied is browse.copied, by count:
//   - one: "copied 1 line"
//   - other: "copied {n} lines"
func BrowseCopied(n int) string { return count("browse.copied", n, map[string]any{"n": n}) }

// BrowseDateFormat is browse.date_format: "dates look like 2026-09-24"
func BrowseDateFormat() string { return get("browse.date_format", nil) }

// BrowseDatePrompt is browse.date_prompt: "go to date (YYYY-MM-DD): "
func BrowseDatePrompt() string { return get("browse.date_prompt", nil) }

// BrowseExcludeNeedsRange is browse.exclude_needs_range: "exclude works inside a marked range"
func BrowseExcludeNeedsRange() string { return get("browse.exclude_needs_range", nil) }

// BrowseFileExists is browse.file_exists: "{file} exists; pick another name"
func BrowseFileExists(file any) string {
	return get("browse.file_exists", map[string]any{"file": file})
}

// BrowseFindPrompt is browse.find_prompt: "find: "
func BrowseFindPrompt() string { return get("browse.find_prompt", nil) }

// BrowseFindStatus is browse.find_status: "find: {find} {i}/{n}"
func BrowseFindStatus(find, i any, n int) string {
	return get("browse.find_status", map[string]any{"find": find, "i": i, "n": n})
}

// BrowseFormatPrompt is browse.format_prompt: "export as (p)lain · (a)nsi · (h)tml   esc cancel"
func BrowseFormatPrompt() string { return get("browse.format_prompt", nil) }

// BrowseFormatPromptDefault is browse.format_prompt_default: "export as (p)lain · (a)nsi · (h)tml · enter {format}   esc cancel"
func BrowseFormatPromptDefault(format any) string {
	return get("browse.format_prompt_default", map[string]any{"format": format})
}

// BrowseHints is browse.hints: "m mark · space exclude · / find · n/N · g date · 1-9 tags · e export · c copy · esc back"
func BrowseHints() string { return get("browse.hints", nil) }

// BrowseLinesInRange is browse.lines_in_range, by count:
//   - one: "1 line in range"
//   - other: "{n} lines in range"
func BrowseLinesInRange(n int) string {
	return count("browse.lines_in_range", n, map[string]any{"n": n})
}

// BrowseLoading is browse.loading: "loading older history…"
func BrowseLoading() string { return get("browse.loading", nil) }

// BrowseLog is browse.log: "LOG"
func BrowseLog() string { return get("browse.log", nil) }

// BrowseMarkRange is browse.mark_range: "mark a range with m (only received lines export)"
func BrowseMarkRange() string { return get("browse.mark_range", nil) }

// BrowseNoExportDir is browse.no_export_dir: "no export_dir configured; give a full path"
func BrowseNoExportDir() string { return get("browse.no_export_dir", nil) }

// BrowseNoFileName is browse.no_file_name: "no file name given"
func BrowseNoFileName() string { return get("browse.no_file_name", nil) }

// BrowseNoLogs is browse.no_logs: "no logs yet"
func BrowseNoLogs() string { return get("browse.no_logs", nil) }

// BrowseNoLogsAfter is browse.no_logs_after: "no logs on or after {day}"
func BrowseNoLogsAfter(day any) string {
	return get("browse.no_logs_after", map[string]any{"day": day})
}

// BrowseNoMatches is browse.no_matches: "no matches for {find:%q}"
func BrowseNoMatches(find any) string { return get("browse.no_matches", map[string]any{"find": find}) }

// BrowseNothingLeft is browse.nothing_left: "nothing left to export"
func BrowseNothingLeft() string { return get("browse.nothing_left", nil) }

// BrowseNothingToExport is browse.nothing_to_export: "nothing to export"
func BrowseNothingToExport() string { return get("browse.nothing_to_export", nil) }

// BrowseRangeStart is browse.range_start: "range start marked; m again at the end"
func BrowseRangeStart() string { return get("browse.range_start", nil) }

// BrowseReadingLogs is browse.reading_logs: "reading logs: {err}"
func BrowseReadingLogs(err error) string {
	return get("browse.reading_logs", map[string]any{"err": err})
}

// BrowseSavePrompt is browse.save_prompt: "save as: "
func BrowseSavePrompt() string { return get("browse.save_prompt", nil) }

// BrowseSaved is browse.saved: "saved {path}"
func BrowseSaved(path any) string { return get("browse.saved", map[string]any{"path": path}) }

// BrowseTags is browse.tags: "tags:"
func BrowseTags() string { return get("browse.tags", nil) }

// BrowseToToday is browse.to_today: "{first} → today"
func BrowseToToday(first any) string { return get("browse.to_today", map[string]any{"first": first}) }

// CliError is cli.error: "kiln: {err}"
func CliError(err error) string { return get("cli.error", map[string]any{"err": err}) }

// CliLogWriteFailed is cli.log_write_failed: "log write failed: {err}"
func CliLogWriteFailed(err error) string {
	return get("cli.log_write_failed", map[string]any{"err": err})
}

// CliNoCharacter is cli.no_character: "no character {world}/{char}"
func CliNoCharacter(world, char any) string {
	return get("cli.no_character", map[string]any{"world": world, "char": char})
}

// CliNoCharacterDefine is cli.no_character_define: "no character {world}/{char}"
func CliNoCharacterDefine(world, char any) string {
	return get("cli.no_character_define", map[string]any{"world": world, "char": char})
}

// CliNoWorld is cli.no_world: "no world {world}"
func CliNoWorld(world any) string { return get("cli.no_world", map[string]any{"world": world}) }

// CliNotSent is cli.not_sent: "not sent: {err}"
func CliNotSent(err error) string { return get("cli.not_sent", map[string]any{"err": err}) }

// CliPasswordPrompt is cli.password_prompt: "password for {world}/{char}: "
func CliPasswordPrompt(world, char any) string {
	return get("cli.password_prompt", map[string]any{"world": world, "char": char})
}

// CliStoreNone is cli.store_none: "password store disabled"
func CliStoreNone() string { return get("cli.store_none", nil) }

// CliTrustHint is cli.trust_hint: "if you expected this, run: kiln trust {world} {fingerprint}"
func CliTrustHint(world, fingerprint any) string {
	return get("cli.trust_hint", map[string]any{"world": world, "fingerprint": fingerprint})
}

// CliUsage is cli.usage: "usage:\n  kiln\n  kiln tail <world> <char>\n  kiln passwd <world> <char>\n  kiln trust <world> <fingerprint>"
func CliUsage() string { return get("cli.usage", nil) }

// ConfigAddedByHighlight is config.added_by_highlight: "added by /highlight"
func ConfigAddedByHighlight() string { return get("config.added_by_highlight", nil) }

// ConfigAddedByKiln is config.added_by_kiln: "added by Kiln"
func ConfigAddedByKiln() string { return get("config.added_by_kiln", nil) }

// ConfigBadCharacterId is config.bad_character_id: "{where}: id may only use letters, digits, _ and -"
func ConfigBadCharacterId(where any) string {
	return get("config.bad_character_id", map[string]any{"where": where})
}

// ConfigBadExportFormat is config.bad_export_format: "config.toml: export_format must be \"plain\", \"ansi\" or \"html\""
func ConfigBadExportFormat() string { return get("config.bad_export_format", nil) }

// ConfigBadHighlightScope is config.bad_highlight_scope: "highlight rule {n}: scope must be \"line\" or \"match\""
func ConfigBadHighlightScope(n int) string {
	return get("config.bad_highlight_scope", map[string]any{"n": n})
}

// ConfigBadHost is config.bad_host: "host must be a hostname or address"
func ConfigBadHost() string { return get("config.bad_host", nil) }

// ConfigBadMaxLineBytes is config.bad_max_line_bytes: "max_line_bytes must be positive"
func ConfigBadMaxLineBytes() string { return get("config.bad_max_line_bytes", nil) }

// ConfigBadNewlineMode is config.bad_newline_mode: "newline_mode must be \"batch\" or \"flatten\""
func ConfigBadNewlineMode() string { return get("config.bad_newline_mode", nil) }

// ConfigBadNotifyIdle is config.bad_notify_idle: "config.toml: notify_idle must be a duration like \"5m\" (\"0\" turns it off)"
func ConfigBadNotifyIdle() string { return get("config.bad_notify_idle", nil) }

// ConfigBadPackId is config.bad_pack_id: "pack id {id:%q} may only use letters, digits, _ and -"
func ConfigBadPackId(id any) string { return get("config.bad_pack_id", map[string]any{"id": id}) }

// ConfigBadPasswordStore is config.bad_password_store: "config.toml: password_store must be \"keychain\", \"file\" or \"none\""
func ConfigBadPasswordStore() string { return get("config.bad_password_store", nil) }

// ConfigBadPort is config.bad_port: "{file}: port must be 1-65535"
func ConfigBadPort(file any) string { return get("config.bad_port", map[string]any{"file": file}) }

// ConfigBadTlsTrust is config.bad_tls_trust: "{file}: tls_trust must be \"pin\" or \"ca\""
func ConfigBadTlsTrust(file any) string {
	return get("config.bad_tls_trust", map[string]any{"file": file})
}

// ConfigBadWorldId is config.bad_world_id: "{file}: world id {id:%q} may only use letters, digits, _ and -"
func ConfigBadWorldId(file, id any) string {
	return get("config.bad_world_id", map[string]any{"file": file, "id": id})
}

// ConfigBadWorldIdBare is config.bad_world_id_bare: "bad world id {id:%q}"
func ConfigBadWorldIdBare(id any) string {
	return get("config.bad_world_id_bare", map[string]any{"id": id})
}

// ConfigCharacterId is config.character_id: "{file}: characters {id:%q}"
func ConfigCharacterId(file, id any) string {
	return get("config.character_id", map[string]any{"file": file, "id": id})
}

// ConfigCharacterIdTaken is config.character_id_taken: "{world} already has a character with id {id:%q}"
func ConfigCharacterIdTaken(world, id any) string {
	return get("config.character_id_taken", map[string]any{"world": world, "id": id})
}

// ConfigCharacterNumber is config.character_number: "{file}: characters #{n}"
func ConfigCharacterNumber(file any, n int) string {
	return get("config.character_number", map[string]any{"file": file, "n": n})
}

// ConfigClassifyBadPattern is config.classify_bad_pattern: "classify rule {n} ({tags}): {err}"
func ConfigClassifyBadPattern(n int, tags any, err error) string {
	return get("config.classify_bad_pattern", map[string]any{"n": n, "tags": tags, "err": err})
}

// ConfigClassifyNeedsTag is config.classify_needs_tag: "classify rule {n}: tag or tags is required"
func ConfigClassifyNeedsTag(n int) string {
	return get("config.classify_needs_tag", map[string]any{"n": n})
}

// ConfigDuplicateCharacterId is config.duplicate_character_id: "{where}: id already used"
func ConfigDuplicateCharacterId(where any) string {
	return get("config.duplicate_character_id", map[string]any{"where": where})
}

// ConfigHighlightBadPattern is config.highlight_bad_pattern: "highlight rule {n}: {err}"
func ConfigHighlightBadPattern(n int, err error) string {
	return get("config.highlight_bad_pattern", map[string]any{"n": n, "err": err})
}

// ConfigHighlightNeedsMatch is config.highlight_needs_match: "highlight rule {n}: match needs tags or pattern"
func ConfigHighlightNeedsMatch(n int) string {
	return get("config.highlight_needs_match", map[string]any{"n": n})
}

// ConfigHostRequired is config.host_required: "{file}: host is required"
func ConfigHostRequired(file any) string {
	return get("config.host_required", map[string]any{"file": file})
}

// ConfigLogNameHasFolders is config.log_name_has_folders: "config.toml: log_name is a file name; put folders in log_dir"
func ConfigLogNameHasFolders() string { return get("config.log_name_has_folders", nil) }

// ConfigMissingCharacterTable is config.missing_character_table: "{file}: can't find character {id:%q}'s table"
func ConfigMissingCharacterTable(file, id any) string {
	return get("config.missing_character_table", map[string]any{"file": file, "id": id})
}

// ConfigNameBadChar is config.name_bad_char: "a name can't have {char:%c}"
func ConfigNameBadChar(char any) string {
	return get("config.name_bad_char", map[string]any{"char": char})
}

// ConfigNameBadStart is config.name_bad_start: "a name can't start with {char:%c}"
func ConfigNameBadStart(char any) string {
	return get("config.name_bad_start", map[string]any{"char": char})
}

// ConfigNameHasSpaces is config.name_has_spaces: "a name can't have spaces"
func ConfigNameHasSpaces() string { return get("config.name_has_spaces", nil) }

// ConfigNameNotAscii is config.name_not_ascii: "a name can only use plain ASCII"
func ConfigNameNotAscii() string { return get("config.name_not_ascii", nil) }

// ConfigNameRequired is config.name_required: "{where}: name is required"
func ConfigNameRequired(where any) string {
	return get("config.name_required", map[string]any{"where": where})
}

// ConfigNameRequiredBare is config.name_required_bare: "name is required"
func ConfigNameRequiredBare() string { return get("config.name_required_bare", nil) }

// ConfigNameReserved is config.name_reserved: "{name:%q} isn't allowed as a name"
func ConfigNameReserved(name any) string {
	return get("config.name_reserved", map[string]any{"name": name})
}

// ConfigNoCharacterInWorld is config.no_character_in_world: "{world} has no character {id:%q}"
func ConfigNoCharacterInWorld(world, id any) string {
	return get("config.no_character_in_world", map[string]any{"world": world, "id": id})
}

// ConfigNothingToHighlight is config.nothing_to_highlight: "nothing to highlight"
func ConfigNothingToHighlight() string { return get("config.nothing_to_highlight", nil) }

// ConfigPortRange is config.port_range: "port must be 1-65535"
func ConfigPortRange() string { return get("config.port_range", nil) }

// ConfigUnknownKey is config.unknown_key: "{file}: unknown key {key:%q}"
func ConfigUnknownKey(file, key any) string {
	return get("config.unknown_key", map[string]any{"file": file, "key": key})
}

// ConfigUnknownPack is config.unknown_pack: "unknown pack {id:%q}"
func ConfigUnknownPack(id any) string { return get("config.unknown_pack", map[string]any{"id": id}) }

// ConfigWorldExists is config.world_exists: "world {id:%q} already exists"
func ConfigWorldExists(id any) string { return get("config.world_exists", map[string]any{"id": id}) }

// ConfigWorldHasCharacters is config.world_has_characters: "{world} still has characters"
func ConfigWorldHasCharacters(world any) string {
	return get("config.world_has_characters", map[string]any{"world": world})
}

// ConfigWorldIdChars is config.world_id_chars: "world id may only use letters, digits, _ and -"
func ConfigWorldIdChars() string { return get("config.world_id_chars", nil) }

// ConnBadFingerprint is conn.bad_fingerprint: "malformed sha256 fingerprint {fp:%q}"
func ConnBadFingerprint(fp any) string { return get("conn.bad_fingerprint", map[string]any{"fp": fp}) }

// ConnCertChanged is conn.cert_changed: "certificate for {host} changed: pinned {pinned}, got {got}"
func ConnCertChanged(host, pinned, got any) string {
	return get("conn.cert_changed", map[string]any{"host": host, "pinned": pinned, "got": got})
}

// ConnNoCertificate is conn.no_certificate: "server sent no certificate"
func ConnNoCertificate() string { return get("conn.no_certificate", nil) }

// ConnReadingKnownHosts is conn.reading_known_hosts: "reading known_hosts: {err}"
func ConnReadingKnownHosts(err error) string {
	return get("conn.reading_known_hosts", map[string]any{"err": err})
}

// DateDay is date.day: "Mon Jan 2"
func DateDay() string { return get("date.day", nil) }

// DateDayTime is date.day_time: "Mon Jan 2 15:04"
func DateDayTime() string { return get("date.day_time", nil) }

// DateDayYear is date.day_year: "Mon Jan 2 2006"
func DateDayYear() string { return get("date.day_year", nil) }

// EditorAliases is editor.aliases: "Aliases"
func EditorAliases() string { return get("editor.aliases", nil) }

// EditorAutoconnect is editor.autoconnect: "Autoconnect"
func EditorAutoconnect() string { return get("editor.autoconnect", nil) }

// EditorBytesNumber is editor.bytes_number: "a number of bytes"
func EditorBytesNumber() string { return get("editor.bytes_number", nil) }

// EditorCertTrust is editor.cert_trust: "Cert trust"
func EditorCertTrust() string { return get("editor.cert_trust", nil) }

// EditorDefault is editor.default: "default ({value})"
func EditorDefault(value any) string { return get("editor.default", map[string]any{"value": value}) }

// EditorDefaultHint is editor.default_hint: "default: {value}"
func EditorDefaultHint(value any) string {
	return get("editor.default_hint", map[string]any{"value": value})
}

// EditorDeleteCharacter is editor.delete_character: "Delete character"
func EditorDeleteCharacter() string { return get("editor.delete_character", nil) }

// EditorDeleteCharacterWarning is editor.delete_character_warning: "Enter again to delete {what} and forget the password"
func EditorDeleteCharacterWarning(what any) string {
	return get("editor.delete_character_warning", map[string]any{"what": what})
}

// EditorDeleteWorld is editor.delete_world: "Delete world"
func EditorDeleteWorld() string { return get("editor.delete_world", nil) }

// EditorDeleteWorldWarning is editor.delete_world_warning: "Enter again to delete {world}"
func EditorDeleteWorldWarning(world any) string {
	return get("editor.delete_world_warning", map[string]any{"world": world})
}

// EditorDeleted is editor.deleted: "deleted {what} (logs kept)"
func EditorDeleted(what any) string { return get("editor.deleted", map[string]any{"what": what}) }

// EditorDeletedPasswordKept is editor.deleted_password_kept: "deleted {what}, but its password wasn't: {err}"
func EditorDeletedPasswordKept(what any, err error) string {
	return get("editor.deleted_password_kept", map[string]any{"what": what, "err": err})
}

// EditorEditing is editor.editing: "Editing {name}"
func EditorEditing(name any) string { return get("editor.editing", map[string]any{"name": name}) }

// EditorExtra is editor.extra: "More settings"
func EditorExtra() string { return get("editor.extra", nil) }

// EditorForgetPassword is editor.forget_password: "Forget saved password"
func EditorForgetPassword() string { return get("editor.forget_password", nil) }

// EditorForgotPassword is editor.forgot_password: "forgot {world}/{char}'s saved password"
func EditorForgotPassword(world, char any) string {
	return get("editor.forgot_password", map[string]any{"world": world, "char": char})
}

// EditorHint is editor.hint: "Esc to cancel"
func EditorHint() string { return get("editor.hint", nil) }

// EditorHost is editor.host: "Host"
func EditorHost() string { return get("editor.host", nil) }

// EditorHostSpaces is editor.host_spaces: "a host can't have spaces"
func EditorHostSpaces() string { return get("editor.host_spaces", nil) }

// EditorLocalEcho is editor.local_echo: "Local echo"
func EditorLocalEcho() string { return get("editor.local_echo", nil) }

// EditorLogin is editor.login: "Login"
func EditorLogin() string { return get("editor.login", nil) }

// EditorMaxBytes is editor.max_bytes: "Max bytes"
func EditorMaxBytes() string { return get("editor.max_bytes", nil) }

// EditorNewWorld is editor.new_world: "New world"
func EditorNewWorld() string { return get("editor.new_world", nil) }

// EditorNewlines is editor.newlines: "Newlines"
func EditorNewlines() string { return get("editor.newlines", nil) }

// EditorNone is editor.none: "none"
func EditorNone() string { return get("editor.none", nil) }

// EditorNotify is editor.notify: "Notify"
func EditorNotify() string { return get("editor.notify", nil) }

// EditorOff is editor.off: "off"
func EditorOff() string { return get("editor.off", nil) }

// EditorOn is editor.on: "on"
func EditorOn() string { return get("editor.on", nil) }

// EditorPacks is editor.packs: "Packs"
func EditorPacks() string { return get("editor.packs", nil) }

// EditorPacksList is editor.packs_list: "pack ids, separated by commas"
func EditorPacksList() string { return get("editor.packs_list", nil) }

// EditorPort is editor.port: "Port"
func EditorPort() string { return get("editor.port", nil) }

// EditorPortNumber is editor.port_number: "a port is a number"
func EditorPortNumber() string { return get("editor.port_number", nil) }

// EditorPortRange is editor.port_range: "port must be 1-65535"
func EditorPortRange() string { return get("editor.port_range", nil) }

// EditorReconnect is editor.reconnect: "Reconnect"
func EditorReconnect() string { return get("editor.reconnect", nil) }

// EditorSave is editor.save: "Save"
func EditorSave() string { return get("editor.save", nil) }

// EditorSaved is editor.saved: "saved {what}"
func EditorSaved(what any) string { return get("editor.saved", map[string]any{"what": what}) }

// EditorTls is editor.tls: "TLS"
func EditorTls() string { return get("editor.tls", nil) }

// EditorWorld is editor.world: "World"
func EditorWorld() string { return get("editor.world", nil) }

// EditorWorldIdChars is editor.world_id_chars: "a world id can only use letters, digits, _ and -"
func EditorWorldIdChars() string { return get("editor.world_id_chars", nil) }

// FormNextField is form.next_field: "Use enter or arrows to move between fields · {hint}"
func FormNextField(hint any) string { return get("form.next_field", map[string]any{"hint": hint}) }

// LogstoreBadDirection is logstore.bad_direction: "logstore: bad direction {dir:%q}"
func LogstoreBadDirection(dir any) string {
	return get("logstore.bad_direction", map[string]any{"dir": dir})
}

// LogstoreBadPrefix is logstore.bad_prefix: "logstore: bad prefix {prefix:%q}"
func LogstoreBadPrefix(prefix any) string {
	return get("logstore.bad_prefix", map[string]any{"prefix": prefix})
}

// LogstoreBadTime is logstore.bad_time: "logstore: bad time: {err}"
func LogstoreBadTime(err error) string { return get("logstore.bad_time", map[string]any{"err": err}) }

// LogstoreNoTab is logstore.no_tab: "logstore: no tab in {line:%q}"
func LogstoreNoTab(line any) string { return get("logstore.no_tab", map[string]any{"line": line}) }

// LogstoreReading is logstore.reading: "logstore: reading {file}: {err}"
func LogstoreReading(file any, err error) string {
	return get("logstore.reading", map[string]any{"file": file, "err": err})
}

// NotifyBadLevel is notify.bad_level: "notify must be \"all\", \"first\", \"attention\" or \"none\""
func NotifyBadLevel() string { return get("notify.bad_level", nil) }

// NotifyBadMethod is notify.bad_method: "notify_method must be \"osc\", \"bell\" or \"both\""
func NotifyBadMethod() string { return get("notify.bad_method", nil) }

// NotifyHeldMore is notify.held_more: "{msg} (+{n} more)"
func NotifyHeldMore(msg any, n int) string {
	return get("notify.held_more", map[string]any{"msg": msg, "n": n})
}

// NotifyLevel is notify.level: "notify level: {level}"
func NotifyLevel(level any) string { return get("notify.level", map[string]any{"level": level}) }

// NotifyLevelOverride is notify.level_override: "{level} (overridden from {config})"
func NotifyLevelOverride(level, config any) string {
	return get("notify.level_override", map[string]any{"level": level, "config": config})
}

// NotifyLevelUntilQuit is notify.level_until_quit: "{name} notify level set to {level} for this session"
func NotifyLevelUntilQuit(name, level any) string {
	return get("notify.level_until_quit", map[string]any{"name": name, "level": level})
}

// PathfmtTrailingPercent is pathfmt.trailing_percent: "% at the end (use %% for a %)"
func PathfmtTrailingPercent() string { return get("pathfmt.trailing_percent", nil) }

// PathfmtUnknownPlaceholder is pathfmt.unknown_placeholder: "unknown placeholder {{{name}}} (use {vars})"
func PathfmtUnknownPlaceholder(name, vars any) string {
	return get("pathfmt.unknown_placeholder", map[string]any{"name": name, "vars": vars})
}

// PathfmtUnknownTimeCode is pathfmt.unknown_time_code: "unknown time code %{code:%c}"
func PathfmtUnknownTimeCode(code any) string {
	return get("pathfmt.unknown_time_code", map[string]any{"code": code})
}

// PickerAddCharHint is picker.add_char_hint: "Enter to connect · Esc to cancel"
func PickerAddCharHint() string { return get("picker.add_char_hint", nil) }

// PickerAddCharacter is picker.add_character: "+ Character"
func PickerAddCharacter() string { return get("picker.add_character", nil) }

// PickerAddWorld is picker.add_world: "+ World"
func PickerAddWorld() string { return get("picker.add_world", nil) }

// PickerBlockedByLog is picker.blocked_by_log: "Exit log mode first"
func PickerBlockedByLog() string { return get("picker.blocked_by_log", nil) }

// PickerBlockedByQuestion is picker.blocked_by_question: "Answer the question first"
func PickerBlockedByQuestion() string { return get("picker.blocked_by_question", nil) }

// PickerFilter is picker.filter: "Filter"
func PickerFilter() string { return get("picker.filter", nil) }

// PickerHint is picker.hint: "Enter to connect · Esc to close"
func PickerHint() string { return get("picker.hint", nil) }

// PickerName is picker.name: "Name"
func PickerName() string { return get("picker.name", nil) }

// ScrollbackHistoryEnds is scrollback.history_ends: "─── history ends {when} ───"
func ScrollbackHistoryEnds(when any) string {
	return get("scrollback.history_ends", map[string]any{"when": when})
}

// ScrollbackLoading is scrollback.loading: "─── loading older history… ───"
func ScrollbackLoading() string { return get("scrollback.loading", nil) }

// SecretsStoreNone is secrets.store_none: "password_store is \"none\""
func SecretsStoreNone() string { return get("secrets.store_none", nil) }

// Separator is separator: " · "
func Separator() string { return get("separator", nil) }

// SessionClosedByServer is session.closed_by_server: "closed by server"
func SessionClosedByServer() string { return get("session.closed_by_server", nil) }

// SessionConnectFailed is session.connect_failed: "connect failed: {err}"
func SessionConnectFailed(err error) string {
	return get("session.connect_failed", map[string]any{"err": err})
}

// SessionConnectFailedRetrying is session.connect_failed_retrying: "connect failed: {err}; retrying in {delay}"
func SessionConnectFailedRetrying(err error, delay any) string {
	return get("session.connect_failed_retrying", map[string]any{"err": err, "delay": delay})
}

// SessionConnected is session.connected: "connected to {host}:{port}"
func SessionConnected(host, port any) string {
	return get("session.connected", map[string]any{"host": host, "port": port})
}

// SessionDisconnected is session.disconnected: "disconnected ({reason})"
func SessionDisconnected(reason any) string {
	return get("session.disconnected", map[string]any{"reason": reason})
}

// SessionDisconnectedRetrying is session.disconnected_retrying: "disconnected ({reason}); retrying in {delay}"
func SessionDisconnectedRetrying(reason, delay any) string {
	return get("session.disconnected_retrying", map[string]any{"reason": reason, "delay": delay})
}

// SessionNoSavedPassword is session.no_saved_password: "no saved password for {world}/{char}"
func SessionNoSavedPassword(world, char any) string {
	return get("session.no_saved_password", map[string]any{"world": world, "char": char})
}

// SessionNotConnected is session.not_connected: "not connected"
func SessionNotConnected() string { return get("session.not_connected", nil) }

// SessionQuit is session.quit: "disconnected (quit)"
func SessionQuit() string { return get("session.quit", nil) }

// SessionSentNotLogged is session.sent_not_logged: "sent, but not logged: {err}"
func SessionSentNotLogged(err error) string {
	return get("session.sent_not_logged", map[string]any{"err": err})
}

// SidebarOpenConnection is sidebar.open_connection: "+ Connection"
func SidebarOpenConnection() string { return get("sidebar.open_connection", nil) }

// StateConnected is state.connected: "connected"
func StateConnected() string { return get("state.connected", nil) }

// StateConnecting is state.connecting: "connecting"
func StateConnecting() string { return get("state.connecting", nil) }

// StateDisconnected is state.disconnected: "disconnected"
func StateDisconnected() string { return get("state.disconnected", nil) }

// StateFailed is state.failed: "failed"
func StateFailed() string { return get("state.failed", nil) }

// StatusAlreadyConnected is status.already_connected: "{name} is already connected"
func StatusAlreadyConnected(name any) string {
	return get("status.already_connected", map[string]any{"name": name})
}

// StatusAway is status.away: "away until your next key or click"
func StatusAway() string { return get("status.away", nil) }

// StatusCertChanged is status.cert_changed: "{name}: certificate changed; /trust to accept"
func StatusCertChanged(name any) string {
	return get("status.cert_changed", map[string]any{"name": name})
}

// StatusConfigNotReloaded is status.config_not_reloaded: "config not reloaded: {err}"
func StatusConfigNotReloaded(err error) string {
	return get("status.config_not_reloaded", map[string]any{"err": err})
}

// StatusConfigReloaded is status.config_reloaded: "config reloaded"
func StatusConfigReloaded() string { return get("status.config_reloaded", nil) }

// StatusCopied is status.copied: "copied to clipboard"
func StatusCopied() string { return get("status.copied", nil) }

// StatusHighlightAdded is status.highlight_added: "added highlight for {text:%q}"
func StatusHighlightAdded(text any) string {
	return get("status.highlight_added", map[string]any{"text": text})
}

// StatusHighlightFailed is status.highlight_failed: "highlight: {err}"
func StatusHighlightFailed(err error) string {
	return get("status.highlight_failed", map[string]any{"err": err})
}

// StatusKeychainFailed is status.keychain_failed: "keychain: {err} (set password_store = \"file\" or \"none\" in config.toml)"
func StatusKeychainFailed(err error) string {
	return get("status.keychain_failed", map[string]any{"err": err})
}

// StatusLinkFailed is status.link_failed: "can't open link: {err}"
func StatusLinkFailed(err error) string { return get("status.link_failed", map[string]any{"err": err}) }

// StatusLinkOpened is status.link_opened: "opened {url}"
func StatusLinkOpened(url any) string { return get("status.link_opened", map[string]any{"url": url}) }

// StatusLogWriteFailed is status.log_write_failed: "{name}: log write failed: {err}"
func StatusLogWriteFailed(name any, err error) string {
	return get("status.log_write_failed", map[string]any{"name": name, "err": err})
}

// StatusLoginNotSent is status.login_not_sent: "login not sent: {err}"
func StatusLoginNotSent(err error) string {
	return get("status.login_not_sent", map[string]any{"err": err})
}

// StatusNeedsCharacter is status.needs_character: "{command} needs an open character"
func StatusNeedsCharacter(command any) string {
	return get("status.needs_character", map[string]any{"command": command})
}

// StatusNoChangedCert is status.no_changed_cert: "no changed certificate to trust"
func StatusNoChangedCert() string { return get("status.no_changed_cert", nil) }

// StatusNotConnected is status.not_connected: "{name} is not connected (/connect)"
func StatusNotConnected(name any) string {
	return get("status.not_connected", map[string]any{"name": name})
}

// StatusNotSent is status.not_sent: "not sent: {err}"
func StatusNotSent(err error) string { return get("status.not_sent", map[string]any{"err": err}) }

// StatusNothingOpen is status.nothing_open: "nothing open to send to"
func StatusNothingOpen() string { return get("status.nothing_open", nil) }

// StatusOverLimit is status.over_limit: "over {n} bytes: Enter again to send anyway"
func StatusOverLimit(n int) string { return get("status.over_limit", map[string]any{"n": n}) }

// StatusPasswordNotSaved is status.password_not_saved: "password not saved"
func StatusPasswordNotSaved() string { return get("status.password_not_saved", nil) }

// StatusPasswordNotSavedErr is status.password_not_saved_err: "password not saved: {err}"
func StatusPasswordNotSavedErr(err error) string {
	return get("status.password_not_saved_err", map[string]any{"err": err})
}

// StatusPasswordSaved is status.password_saved: "password saved"
func StatusPasswordSaved() string { return get("status.password_saved", nil) }

// StatusQuitHint is status.quit_hint: "Press Ctrl+{key} again to quit"
func StatusQuitHint(key any) string { return get("status.quit_hint", map[string]any{"key": key}) }

// StatusSkippedLogin is status.skipped_login: "skipped login"
func StatusSkippedLogin() string { return get("status.skipped_login", nil) }

// StatusTrustFailed is status.trust_failed: "trust: {err}"
func StatusTrustFailed(err error) string {
	return get("status.trust_failed", map[string]any{"err": err})
}

// StatusTrusted is status.trusted: "trusted new certificate for {host}"
func StatusTrusted(host any) string { return get("status.trusted", map[string]any{"host": host}) }

// StatusUnknownCommand is status.unknown_command: "unknown command {command}"
func StatusUnknownCommand(command any) string {
	return get("status.unknown_command", map[string]any{"command": command})
}

// ThemeBadColor is theme.bad_color: "themes/{file}: {where}: {color:%q} isn't a color (use #rrggbb, a palette name, or a terminal color like bright-blue)"
func ThemeBadColor(file, where, color any) string {
	return get("theme.bad_color", map[string]any{"file": file, "where": where, "color": color})
}

// ThemeBadField is theme.bad_field: "themes/{file}: {role}: {field} must be {want}"
func ThemeBadField(file, role, field, want any) string {
	return get("theme.bad_field", map[string]any{"file": file, "role": role, "field": field, "want": want})
}

// ThemeExtendsLoop is theme.extends_loop: "themes/{file}: extends loops back to {name:%q}"
func ThemeExtendsLoop(file, name any) string {
	return get("theme.extends_loop", map[string]any{"file": file, "name": name})
}

// ThemeNoTheme is theme.no_theme: "no theme {name:%q} (no themes/{name}.toml)"
func ThemeNoTheme(name any) string { return get("theme.no_theme", map[string]any{"name": name}) }

// ThemePaletteEntry is theme.palette_entry: "palette {name}"
func ThemePaletteEntry(name any) string {
	return get("theme.palette_entry", map[string]any{"name": name})
}

// ThemePaletteNameTaken is theme.palette_name_taken: "themes/{file}: palette name {name:%q} is a terminal color"
func ThemePaletteNameTaken(file, name any) string {
	return get("theme.palette_name_taken", map[string]any{"file": file, "name": name})
}

// ThemeParse is theme.parse: "themes/{file}: {err}"
func ThemeParse(file any, err error) string {
	return get("theme.parse", map[string]any{"file": file, "err": err})
}

// ThemeUnknownField is theme.unknown_field: "themes/{file}: {role}: unknown setting {field:%q}"
func ThemeUnknownField(file, role, field any) string {
	return get("theme.unknown_field", map[string]any{"file": file, "role": role, "field": field})
}

// ThemeUnknownKey is theme.unknown_key: "themes/{file}: unknown key {key:%q} (a theme has extends, palette and ui)"
func ThemeUnknownKey(file, key any) string {
	return get("theme.unknown_key", map[string]any{"file": file, "key": key})
}

// ThemeUnknownRole is theme.unknown_role: "themes/{file}: unknown role {role:%q}"
func ThemeUnknownRole(file, role any) string {
	return get("theme.unknown_role", map[string]any{"file": file, "role": role})
}

// ThemeWantBool is theme.want_bool: "true or false"
func ThemeWantBool() string { return get("theme.want_bool", nil) }

// ThemeWantColor is theme.want_color: "a color"
func ThemeWantColor() string { return get("theme.want_color", nil) }

// ThemeWantTheme is theme.want_theme: "a theme name"
func ThemeWantTheme() string { return get("theme.want_theme", nil) }

// ViewCertChanged is view.cert_changed: "Certificate changed · /trust to accept it"
func ViewCertChanged() string { return get("view.cert_changed", nil) }

// ViewConnectFailed is view.connect_failed: "Connection failed · Enter to retry"
func ViewConnectFailed() string { return get("view.connect_failed", nil) }

// ViewConnecting is view.connecting: "Connecting…"
func ViewConnecting() string { return get("view.connecting", nil) }

// ViewDisconnected is view.disconnected: "Disconnected · Enter to connect"
func ViewDisconnected() string { return get("view.disconnected", nil) }

// ViewMoreAbove is view.more_above: "▲ {n} more"
func ViewMoreAbove(n int) string { return get("view.more_above", map[string]any{"n": n}) }

// ViewMoreBelow is view.more_below: "▼ {n} more"
func ViewMoreBelow(n int) string { return get("view.more_below", map[string]any{"n": n}) }

// ViewNoCharacters is view.no_characters: ""
func ViewNoCharacters() string { return get("view.no_characters", nil) }

// ViewNothingOpen is view.nothing_open: "Hit Enter or Ctrl+O to choose a connection"
func ViewNothingOpen() string { return get("view.nothing_open", nil) }

// ViewPasswordKeys is view.password_keys: "   Enter to log in · Esc to skip"
func ViewPasswordKeys() string { return get("view.password_keys", nil) }

// ViewPasswordLabel is view.password_label: "Password for {name}: "
func ViewPasswordLabel(name any) string {
	return get("view.password_label", map[string]any{"name": name})
}

// ViewPillMore is view.pill_more: "▼ more"
func ViewPillMore() string { return get("view.pill_more", nil) }

// ViewPillNew is view.pill_new: "▼ {n} new"
func ViewPillNew(n int) string { return get("view.pill_new", map[string]any{"n": n}) }

// ViewSavePassword is view.save_password: "Save password for {name} in {store}? [Y/n]"
func ViewSavePassword(name, store any) string {
	return get("view.save_password", map[string]any{"name": name, "store": store})
}

// ViewSelected is view.selected: "{n} selected"
func ViewSelected(n int) string { return get("view.selected", map[string]any{"n": n}) }

// ViewStoreFile is view.store_file: "the password file"
func ViewStoreFile() string { return get("view.store_file", nil) }

// ViewStoreKeychain is view.store_keychain: "the keychain"
func ViewStoreKeychain() string { return get("view.store_keychain", nil) }

// ViewTooSmall is view.too_small: "Kiln needs at least {min_w}x{min_h} (now {w}x{h})"
func ViewTooSmall(min_w, min_h, w, h any) string {
	return get("view.too_small", map[string]any{"min_w": min_w, "min_h": min_h, "w": w, "h": h})
}
